---

- hosts: all
  become: true
  pre_tasks:
  
  - name: update repository index
    tags: always
    dnf:
      update_only: yes
      update_cache: yes

#  - name: create ansible user
#    tag: always
#    user:
#      name: ansible
#      group: root 

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php for web servers
    dnf:
      name:
        - httpd
        - php
        - firewalld
        - unzip
      state: latest 

  - name: start httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: start firewalld service
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: copy default html files for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: change email address for admin
    tags: apache,rocky,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin ravi@ansible.com 
    register: httpd

  - name: restart httpd
    tags: apache,rocky,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

- hosts: rocky
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: installing terraform from remote source and unziping it
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package
    dnf:
      name: mariadb-server
      state: latest

  - name: start mariadb service
    service:
      name: mariadb
      state: started
      enabled: yes
